
eia_symbols = {
    'PET.WCRSTUS1.W': 'Weekly U.S. Ending Stocks of Crude Oil  (Thousand Barrels)',
    'PET.WCESTUS1.W': 'Weekly U.S. Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.WCSSTUS1.W': 'Weekly U.S. Ending Stocks of Crude Oil in SPR  (Thousand Barrels)',
    'PET.WGTSTUS1.W': 'Weekly U.S. Ending Stocks of Total Gasoline  (Thousand Barrels)',
    'PET.WGRSTUS1.W': 'Weekly U.S. Ending Stocks of Reformulated Motor Gasoline  (Thousand Barrels)',
    'PET.WG4ST_NUS_1.W': 'Weekly U.S. Ending Stocks of Conventional Motor Gasoline  (Thousand Barrels)',
    'PET.WBCSTUS1.W': 'Weekly U.S. Ending Stocks of Gasoline Blending Components  (Thousand Barrels)',
    'PET.W_EPOOXE_SAE_NUS_MBBL.W': 'Weekly U.S. Ending Stocks of Fuel Ethanol  (Thousand Barrels)',
    'PET.WKJSTUS1.W': 'Weekly U.S. Ending Stocks of Kerosene-Type Jet Fuel  (Thousand Barrels)',
    'PET.WDISTUS1.W': 'Weekly U.S. Ending Stocks of Distillate Fuel Oil  (Thousand Barrels)',
    'PET.WD0ST_NUS_1.W': 'Weekly U.S. Ending Stocks of Distillate Fuel Oil, 0 to 15 ppm Sulfur  (Thousand Barrels)',
    'PET.WD1ST_NUS_1.W': 'Weekly U.S. Ending Stocks of Distillate Fuel Oil, Greater than 15 to 500 ppm Sulfur  (Thousand Barrels)',
    'PET.WDGSTUS1.W': 'Weekly U.S. Ending Stocks of Distillate Fuel Oil, Greater Than 500 ppm Sulfur  (Thousand Barrels)',
    'PET.WRESTUS1.W': 'Weekly U.S. Ending Stocks of Residual Fuel Oil  (Thousand Barrels)',
    'PET.WPRSTUS1.W': 'Weekly U.S. Ending Stocks of Propane and Propylene  (Thousand Barrels)',
    'PET.W_EPPO6_SAE_NUS_MBBL.W': 'Weekly U.S. Ending Stocks of Other Oils (Excluding Fuel Ethanol)  (Thousand Barrels)',
    'PET.WUOSTUS1.W': 'Weekly U.S. Ending Stocks of Unfinished Oils  (Thousand Barrels)',
    'PET.WTTSTUS1.W': 'Weekly U.S. Ending Stocks of Crude Oil and Petroleum Products  (Thousand Barrels)',
    'PET.WTESTUS1.W': 'Weekly U.S. Ending Stocks excluding SPR of Crude Oil and Petroleum Products  (Thousand Barrels)',
    'PET.WCESTP11.W': 'Weekly East Coast (PADD 1) Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.WCESTP21.W': 'Weekly Midwest (PADD 2) Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.W_EPC0_SAX_YCUOK_MBBL.W': 'Weekly Cushing, OK Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.WCESTP31.W': 'Weekly Gulf Coast (PADD 3) Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.WCESTP41.W': 'Weekly Rocky Mountain (PADD 4) Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.WCESTP51.W': 'Weekly West Coast (PADD 5) Ending Stocks excluding SPR of Crude Oil  (Thousand Barrels)',
    'PET.W_EPC0_SKA_NUS_MBBL.W': 'Weekly U.S. Crude Oil Stocks in Transit (on Ships) from Alaska  (Thousand Barrels)',
}